#!/data/data/com.termux/files/usr/bin/sh

export CUSTOM_DEV_NAME=""

if [ "$CUSTOM_DEV_NAME" = "" ]; then
    export TERMUX_INFO="$(termux-info)"
    export MANUFACTURER_NAME="$(echo "$TERMUX_INFO" | grep -A 1 "Device manufacturer:" | tail -1)"
    export MODEL_NAME="$(echo "$TERMUX_INFO" | grep -A 1 "Device model:" | tail -1)"
    if [ "$MANUFACTURER_NAME $MODEL_NAME" = " " ]; then 
        export PLAYER_NAME="Android"
    else
        export PLAYER_NAME="Android - $MANUFACTURER_NAME $MODEL_NAME"
    fi
else
    export PLAYER_NAME="Android - $CUSTOM_DEV_NAME"
fi

$PREFIX/bin/squeezelite -n "$PLAYER_NAME"
