#!/data/data/com.termux/files/usr/bin/sh
. $HOME/wyoming.conf
export VERSION=1

wlog() {
    local message="$1"
    echo "$message" 2>&1 | tee -a "$HOME/wyoming-events.log"
}

if [ "$CUSTOM_DEV_NAME" = "" ]; then
    export TERMUX_INFO="$(termux-info)"
    export MANUFACTURER_NAME="$(echo "$TERMUX_INFO" | grep -A 1 "Device manufacturer:" | tail -1)"
    export MODEL_NAME="$(echo "$TERMUX_INFO" | grep -A 1 "Device model:" | tail -1)"
    if [ "$MANUFACTURER_NAME $MODEL_NAME" = " " ]; then 
        export SATELLITE_NAME="Android Satellite"
    else
        export SATELLITE_NAME="$MANUFACTURER_NAME $MODEL_NAME"
    fi
else
    export SATELLITE_NAME="$CUSTOM_DEV_NAME"
fi

export EVENT_HANDLER_FLAGS="--uri tcp://127.0.0.1:10500 --hass-token \"$HASS_TOKEN\" --hass-url \"$HASS_URL\" --wyoming-name \"$SATELLITE_NAME\""
wlog "Enter wyoming-events directory..."
cd "$HOME/wyoming-events"
exec stdbuf -oL -eL python3 ./wyoming-events.py $EVENT_HANDLER_FLAGS 2>&1 | tee -a "$HOME/wyoming-events.log"