#!/data/data/com.termux/files/usr/bin/sh
. $HOME/wyoming.conf
export VERSION=2

wlog() {
    local message="$1"
    echo "$message" 2>&1 | tee -a "$HOME/wyoming-satellite.log"
}

echo "" > "$HOME/wyoming-satellite.log"
wlog "$(date)"

wlog "Ensure sox is available..."
if ! command -v rec > /dev/null 2>&1 || ! command -v play > /dev/null 2>&1; then
    wlog "sox was not found, installing it now..."
    pkg install sox -y
    if ! command -v rec > /dev/null 2>&1 || ! command -v play > /dev/null 2>&1; then
        wlog "ERROR: Failed to install sox" >&2
        exit 1
    fi
fi

if [ "$CUSTOM_DEV_NAME" = "" ]; then
    export TERMUX_INFO="$(termux-info)"
    export MANUFACTURER_NAME="$(echo "$TERMUX_INFO" | grep -A 1 "Device manufacturer:" | tail -1)"
    export MODEL_NAME="$(echo "$TERMUX_INFO" | grep -A 1 "Device model:" | tail -1)"
    if [ "$MANUFACTURER_NAME $MODEL_NAME" = " " ]; then 
        export SATELLITE_NAME="Android Satellite"
    else
        export SATELLITE_NAME="$MANUFACTURER_NAME $MODEL_NAME"
    fi
else
    export SATELLITE_NAME="$CUSTOM_DEV_NAME"
fi

if [ "$WW_ENABLED" = "true" ]; then
    sv start wyoming-wakeword || exit 1
    export OWW_FLAGS="--wake-uri tcp://127.0.0.1:10400 --wake-word-name $SELECTED_WAKE_WORD"
else
    export OWW_FLAGS=""
fi

wlog "Ensure module-sles-source is loaded..."
if ! pactl list short modules | grep "module-sles-source" ; then
    pactl load-module module-sles-source
fi

if [ "$EVENTS_ENABLED" = "true" ]; then
    sv start wyoming-events || exit 1
    export EVENTS_FLAGS="--event-uri tcp://127.0.0.1:10500"
else
    export EVENTS_FLAGS=""
fi

wlog "Enter wyoming-satellite directory..."
cd "$HOME/wyoming-satellite"
wlog "Sleeping for 15s to allow wakeword / events to start"
sleep 15
wlog "Starting satellite"
exec stdbuf -oL -eL python3 ./script/run \
--name "$SATELLITE_NAME" \
--no-zeroconf \
--uri 'tcp://0.0.0.0:10700' \
--mic-command 'rec -r 16000 -c 1 -b 16 -e signed-integer -t raw --no-show-progress -' \
--snd-command 'play -r 22050 -c 1 -b 16 -e signed-integer -t raw --no-show-progress -' \
--awake-wav "$WAKESOUND" \
--done-wav "$DONESOUND" \
--timer-finished-wav "$TIMERFINISHEDSOUND" \
--timer-finished-wav-repeat $TIMERFINISHEDREPEAT \
$OWW_FLAGS \
$EVENTS_FLAGS \
--debug 2>&1 | tee -a "$HOME/wyoming-satellite.log"